from typing import Dict, List, Optional

from app.system_visibility.schemas import (
    ArchitectureEdge,
    ArchitectureEdgeKind,
    ArchitectureNode,
    ArchitectureNodeKind,
    ArchitectureNodeMetadata,
    ArchitectureVisibilityGraph,
    ArchitectureVisibilityScope,
    ArchitectureVisibilitySourceBasis,
    ArchitectureVisibilitySummary,
    ProductCapabilityExport,
    ProductDataType,
    ProductExportBundle,
    ProductGroup,
    ProductInventorySummary,
    ProductMappingMetadata,
)


ARCHITECTURE_VISIBILITY_LIMITATIONS = [
    "Architecture visibility is a static v1 inventory curated from repository files.",
    "It is not a live dependency analyzer, graph database, ownership registry, permission model, security control, or persistence layer.",
    "Edges represent known implementation relationships that are useful for navigation; they are not exhaustive import graphs.",
]


class SystemVisibilityService:
    def _product_mapping(
        self,
        *,
        product_name: str,
        homeowner_label: str,
        contractor_label: str,
        ui_section: str,
        ui_card: str,
        ui_priority: int,
        visible_in_v1: bool,
        data_type: ProductDataType,
        homeowner_question_answered: str,
        empty_state_message: str,
    ) -> ProductMappingMetadata:
        return ProductMappingMetadata(
            product_name=product_name,
            homeowner_label=homeowner_label,
            contractor_label=contractor_label,
            ui_section=ui_section,
            ui_card=ui_card,
            ui_priority=ui_priority,
            visible_in_v1=visible_in_v1,
            data_type=data_type,
            homeowner_question_answered=homeowner_question_answered,
            empty_state_message=empty_state_message,
        )

    def _internal_mapping(self, product_name: str = "Internal architecture visibility") -> ProductMappingMetadata:
        return self._product_mapping(
            product_name=product_name,
            homeowner_label="Internal planning surface",
            contractor_label="Internal planning surface",
            ui_section="Internal/Debug",
            ui_card="Internal architecture",
            ui_priority=999,
            visible_in_v1=False,
            data_type=ProductDataType.internal,
            homeowner_question_answered="What internal system surface supports this capability?",
            empty_state_message="This capability is internal and is not shown as a homeowner-facing card.",
        )

    def _node(
        self,
        node_id: str,
        label: str,
        kind: ArchitectureNodeKind,
        *,
        layer: str,
        file_path: str,
        phase: Optional[str] = None,
        read_write_boundary: str = "read_only_visibility_metadata",
        audience: str = "internal",
        related_endpoints: Optional[List[str]] = None,
        related_tests: Optional[List[str]] = None,
        tags: Optional[List[str]] = None,
        product_mapping: Optional[ProductMappingMetadata] = None,
    ) -> ArchitectureNode:
        resolved_product_mapping = product_mapping or self._internal_mapping()
        resolved_tags = sorted({*(tags or []), self._section_tag(resolved_product_mapping.ui_section)})
        return ArchitectureNode(
            id=node_id,
            label=label,
            kind=kind,
            metadata=ArchitectureNodeMetadata(
                layer=layer,
                file_path=file_path,
                phase=phase,
                read_write_boundary=read_write_boundary,
                audience=audience,
                related_endpoints=sorted(related_endpoints or []),
                related_tests=sorted(related_tests or []),
                tags=resolved_tags,
                product_mapping=resolved_product_mapping,
            ),
        )

    def _edge(
        self,
        edge_id: str,
        source: str,
        target: str,
        kind: ArchitectureEdgeKind,
        label: str,
    ) -> ArchitectureEdge:
        return ArchitectureEdge(id=edge_id, source=source, target=target, kind=kind, label=label)

    def _capability_node(
        self,
        node_id: str,
        label: str,
        *,
        product_mapping: ProductMappingMetadata,
        phase: Optional[str] = None,
        file_path: str = "apps/api/app/services/system_visibility.py",
        related_endpoints: Optional[List[str]] = None,
        related_tests: Optional[List[str]] = None,
        tags: Optional[List[str]] = None,
    ) -> ArchitectureNode:
        section_tag = self._section_tag(product_mapping.ui_section)
        return self._node(
            node_id,
            label,
            ArchitectureNodeKind.product_capability,
            layer="product",
            file_path=file_path,
            phase=phase,
            read_write_boundary="product_mapping_metadata_only",
            audience="homeowner-facing / contractor-facing / internal",
            related_endpoints=related_endpoints,
            related_tests=related_tests,
            tags=sorted({*(tags or []), "product", "ui", section_tag}),
            product_mapping=product_mapping,
        )

    def _ui_section_node(self, node_id: str, label: str, priority: int) -> ArchitectureNode:
        mapping = self._product_mapping(
            product_name=f"{label} UI Section",
            homeowner_label=label,
            contractor_label=label,
            ui_section=label,
            ui_card=f"{label} section",
            ui_priority=priority,
            visible_in_v1=label not in {"Internal/Debug", "Deferred/Legacy"},
            data_type=ProductDataType.internal,
            homeowner_question_answered=f"What capabilities are organized into the {label} section?",
            empty_state_message=f"No {label} capabilities are currently mapped.",
        )
        return self._node(
            node_id,
            label,
            ArchitectureNodeKind.ui_section,
            layer="ui",
            file_path="apps/web/src/pages/ArchitecturePage.jsx",
            read_write_boundary="product_mapping_metadata_only",
            audience="internal",
            tags=["ui", self._section_tag(label)],
            product_mapping=mapping,
        )

    def _section_tag(self, ui_section: str) -> str:
        return {
            "Home": "home",
            "Explore": "explore",
            "Planner": "planner",
            "Builder": "builder",
            "Build": "builder",
            "Internal/Debug": "internal",
            "Hidden/Internal": "hidden_internal",
            "Deferred/Legacy": "deferred",
        }.get(ui_section, "hidden_internal")

    def _nodes(self) -> List[ArchitectureNode]:
        endpoint = "/api/system-visibility/architecture"
        test = "apps/api/tests/test_system_visibility.py"
        energy_twin = self._product_mapping(
            product_name="Energy Twin",
            homeowner_label="Energy Twin",
            contractor_label="Home energy record",
            ui_section="Home",
            ui_card="Energy Twin",
            ui_priority=10,
            visible_in_v1=True,
            data_type=ProductDataType.durable_record,
            homeowner_question_answered="What does the system know about my home?",
            empty_state_message="Start the Energy Twin by adding basic home, panel, utility, and load details.",
        )
        energy_passport = self._product_mapping(
            product_name="Energy Passport",
            homeowner_label="Energy Passport",
            contractor_label="Homeowner-safe system summary",
            ui_section="Home",
            ui_card="Energy Passport",
            ui_priority=20,
            visible_in_v1=False,
            data_type=ProductDataType.derived_view,
            homeowner_question_answered="What system summary can I safely review or share later?",
            empty_state_message="Energy Passport becomes useful after system, ownership, and document context are available.",
        )
        readiness = self._product_mapping(
            product_name="Readiness",
            homeowner_label="Readiness",
            contractor_label="Planning readiness context",
            ui_section="Home",
            ui_card="Readiness",
            ui_priority=30,
            visible_in_v1=True,
            data_type=ProductDataType.derived_view,
            homeowner_question_answered="What is ready to review, and what still needs confirmation?",
            empty_state_message="Readiness improves when service, panel, load, equipment, and goal details are recorded.",
        )
        home_facts = self._product_mapping(
            product_name="Home Facts",
            homeowner_label="Home facts",
            contractor_label="Recorded site facts",
            ui_section="Home",
            ui_card="Home Facts",
            ui_priority=40,
            visible_in_v1=True,
            data_type=ProductDataType.durable_record,
            homeowner_question_answered="Which facts are known versus still missing?",
            empty_state_message="Add home, utility, panel, load, and site details to build the fact base.",
        )
        explore_goals = self._product_mapping(
            product_name="Explore Goals",
            homeowner_label="Goals",
            contractor_label="Homeowner goals",
            ui_section="Explore",
            ui_card="Goals",
            ui_priority=10,
            visible_in_v1=True,
            data_type=ProductDataType.workflow,
            homeowner_question_answered="What should the home do next?",
            empty_state_message="Select goals locally before moving into planner templates.",
        )
        explore_learn = self._product_mapping(
            product_name="Explore Learn",
            homeowner_label="Learn",
            contractor_label="Homeowner education context",
            ui_section="Explore",
            ui_card="Learn",
            ui_priority=20,
            visible_in_v1=True,
            data_type=ProductDataType.internal,
            homeowner_question_answered="What plain-language context helps me understand planning terms?",
            empty_state_message="Learning content remains supporting context until source-backed content governance is approved.",
        )
        guided_templates = self._product_mapping(
            product_name="Guided Templates",
            homeowner_label="Guided templates",
            contractor_label="Sandbox template registry and draft context",
            ui_section="Planner",
            ui_card="Guided Templates",
            ui_priority=10,
            visible_in_v1=True,
            data_type=ProductDataType.workflow,
            homeowner_question_answered="Which safe starting patterns can seed a planning draft?",
            empty_state_message="Guided templates are available only as read-only sandbox seed patterns.",
        )
        sandbox_drafts = self._product_mapping(
            product_name="Sandbox Drafts",
            homeowner_label="Sandbox drafts",
            contractor_label="Sandbox draft context",
            ui_section="Planner",
            ui_card="Sandbox Drafts",
            ui_priority=20,
            visible_in_v1=True,
            data_type=ProductDataType.workflow,
            homeowner_question_answered="What assumptions and missing inputs would a draft need before it can mature?",
            empty_state_message="Draft creation and persistence are deferred; current draft cards are placeholders unless explicitly wired.",
        )
        compatibility = self._product_mapping(
            product_name="Compatibility",
            homeowner_label="Compatibility",
            contractor_label="Compatibility review",
            ui_section="Deferred/Legacy",
            ui_card="Compatibility",
            ui_priority=10,
            visible_in_v1=False,
            data_type=ProductDataType.derived_view,
            homeowner_question_answered="Which planning paths look compatible or need review?",
            empty_state_message="Compatibility needs a design path, equipment context, and known home constraints.",
        )
        scenario_builder = self._product_mapping(
            product_name="Comparisons",
            homeowner_label="Comparisons",
            contractor_label="Scenario planning",
            ui_section="Planner",
            ui_card="Comparisons",
            ui_priority=30,
            visible_in_v1=True,
            data_type=ProductDataType.workflow,
            homeowner_question_answered="Which upgrade paths should I compare at a planning level?",
            empty_state_message="Create at least one planning scenario to compare upgrade paths.",
        )
        product_preferences = self._product_mapping(
            product_name="Product Preferences",
            homeowner_label="Product preferences",
            contractor_label="Product preference and install logic",
            ui_section="Deferred/Legacy",
            ui_card="Product Preferences",
            ui_priority=30,
            visible_in_v1=False,
            data_type=ProductDataType.derived_view,
            homeowner_question_answered="What product or install preferences need review before selection?",
            empty_state_message="Product preference mapping needs equipment type, install path, and contractor-review context.",
        )
        planning_intelligence = self._product_mapping(
            product_name="Planning Intelligence",
            homeowner_label="Planning intelligence",
            contractor_label="Planning intelligence context",
            ui_section="Deferred/Legacy",
            ui_card="Planning Intelligence",
            ui_priority=40,
            visible_in_v1=False,
            data_type=ProductDataType.derived_view,
            homeowner_question_answered="What planning context can the system explain without making final recommendations?",
            empty_state_message="Planning intelligence needs structured goals, topology, equipment, and provenance context.",
        )
        proposal_options = self._product_mapping(
            product_name="Proposal Options",
            homeowner_label="Proposal options",
            contractor_label="Proposal option readiness",
            ui_section="Deferred/Legacy",
            ui_card="Proposal Options",
            ui_priority=10,
            visible_in_v1=False,
            data_type=ProductDataType.derived_view,
            homeowner_question_answered="Which proposal option candidates may be organized later?",
            empty_state_message="Proposal options remain unavailable until estimate readiness and scenario context are sufficient.",
        )
        contractor_context = self._product_mapping(
            product_name="Contractor Context",
            homeowner_label="Contractor review context",
            contractor_label="Contractor context",
            ui_section="Deferred/Legacy",
            ui_card="Contractor Context",
            ui_priority=20,
            visible_in_v1=False,
            data_type=ProductDataType.derived_view,
            homeowner_question_answered="What should a contractor review before the plan can move forward?",
            empty_state_message="Contractor context needs enough site, equipment, and confirmation-gate information to be useful.",
        )
        estimate_readiness = self._product_mapping(
            product_name="Estimate Readiness",
            homeowner_label="Estimate readiness",
            contractor_label="Estimate readiness gates",
            ui_section="Builder",
            ui_card="Estimate Readiness",
            ui_priority=20,
            visible_in_v1=True,
            data_type=ProductDataType.derived_view,
            homeowner_question_answered="What is blocking a planning estimate or proposal prep?",
            empty_state_message="Estimate readiness needs scenarios, topology, confirmation gates, and contractor-review context.",
        )
        install_path = self._product_mapping(
            product_name="Install Path",
            homeowner_label="Install path",
            contractor_label="Install path and topology takeoff",
            ui_section="Deferred/Legacy",
            ui_card="Install Path",
            ui_priority=40,
            visible_in_v1=False,
            data_type=ProductDataType.derived_view,
            homeowner_question_answered="What install path questions need field review?",
            empty_state_message="Install path mapping needs topology, equipment, and pathway information.",
        )
        program_intelligence = self._product_mapping(
            product_name="Program Intelligence",
            homeowner_label="Program readiness",
            contractor_label="Program and grid-edge readiness",
            ui_section="Builder",
            ui_card="Program Intelligence",
            ui_priority=30,
            visible_in_v1=False,
            data_type=ProductDataType.derived_view,
            homeowner_question_answered="What utility or program context still needs confirmation?",
            empty_state_message="Program intelligence needs utility, rate-plan, interconnection, equipment, and jurisdiction context.",
        )
        builder_readiness = self._product_mapping(
            product_name="Builder Readiness",
            homeowner_label="Build readiness",
            contractor_label="Project readiness context",
            ui_section="Builder",
            ui_card="Build Readiness",
            ui_priority=10,
            visible_in_v1=True,
            data_type=ProductDataType.derived_view,
            homeowner_question_answered="What must be resolved before a plan can move forward?",
            empty_state_message="Builder remains a readiness surface until project promotion and contractor handoff are approved.",
        )
        product_catalog = self._product_mapping(
            product_name="Product Catalog",
            homeowner_label="Catalog",
            contractor_label="Deferred product catalog",
            ui_section="Deferred/Legacy",
            ui_card="Catalog",
            ui_priority=70,
            visible_in_v1=False,
            data_type=ProductDataType.internal,
            homeowner_question_answered="Which product categories may be organized later?",
            empty_state_message="Catalog is reachable as a hidden route, but Product Catalog Foundation is deferred.",
        )
        post_install_handoff = self._product_mapping(
            product_name="Post-Install Handoff",
            homeowner_label="Post-install handoff",
            contractor_label="Post-install retention and handoff context",
            ui_section="Deferred/Legacy",
            ui_card="Post-Install Handoff",
            ui_priority=60,
            visible_in_v1=False,
            data_type=ProductDataType.derived_view,
            homeowner_question_answered="What follow-up context may matter after installation?",
            empty_state_message="Post-install handoff needs lifecycle, installation, and follow-up context before it can be useful.",
        )
        architecture_cockpit = self._product_mapping(
            product_name="Product Architecture Cockpit",
            homeowner_label="Internal product map",
            contractor_label="Internal product map",
            ui_section="Internal/Debug",
            ui_card="Product Architecture Cockpit",
            ui_priority=10,
            visible_in_v1=True,
            data_type=ProductDataType.internal,
            homeowner_question_answered="How should internal capabilities be organized into product UI sections?",
            empty_state_message="No product capabilities have been mapped yet.",
        )

        return [
            self._ui_section_node("ui-section-home", "Home", 10),
            self._ui_section_node("ui-section-explore", "Explore", 20),
            self._ui_section_node("ui-section-planner", "Planner", 30),
            self._ui_section_node("ui-section-builder", "Builder", 40),
            self._ui_section_node("ui-section-internal-debug", "Internal/Debug", 50),
            self._ui_section_node("ui-section-deferred-legacy", "Deferred/Legacy", 60),
            self._capability_node(
                "capability-energy-twin",
                "Energy Twin",
                product_mapping=energy_twin,
                phase="phase_2b_phase_4",
                file_path="apps/api/app/services/twin_planning_context.py",
                related_endpoints=["/api/twin-planning-context/homes/{home_id}"],
                related_tests=["apps/api/tests/test_twin_planning_context.py"],
            ),
            self._capability_node(
                "capability-energy-passport",
                "Energy Passport",
                product_mapping=energy_passport,
                phase="phase_14",
                file_path="apps/api/app/services/energy_passport.py",
                related_endpoints=["/api/energy-passport/homes/{home_id}"],
                related_tests=["apps/api/tests/test_energy_passport.py"],
            ),
            self._capability_node(
                "capability-readiness",
                "Readiness",
                product_mapping=readiness,
                phase="phase_3_phase_4",
                file_path="apps/api/app/services/twin_planning_context.py",
                related_endpoints=[
                    "/api/twin-planning-context/homes/{home_id}/views/recommendation-eligibility-readiness",
                    "/api/twin-planning-context/homes/{home_id}/views/trust-provenance-readiness-index",
                ],
                related_tests=["apps/api/tests/test_twin_planning_context.py"],
            ),
            self._capability_node(
                "capability-home-facts",
                "Home Facts",
                product_mapping=home_facts,
                phase="phase_1_phase_2b",
                file_path="apps/api/app/homes/router.py",
                related_endpoints=["/api/homes", "/api/panels", "/api/loads"],
                related_tests=["apps/api/tests/test_twin_planning_context.py"],
            ),
            self._capability_node(
                "capability-explore-goals",
                "Explore Goals",
                product_mapping=explore_goals,
                phase="heart_quill_shell_migration",
                file_path="apps/web/src/pages/HeartQuillShellPage.jsx",
                related_endpoints=[],
                related_tests=[],
            ),
            self._capability_node(
                "capability-explore-learn",
                "Explore Learn",
                product_mapping=explore_learn,
                phase="heart_quill_shell_migration",
                file_path="apps/web/src/pages/HeartQuillShellPage.jsx",
                related_endpoints=[],
                related_tests=[],
            ),
            self._capability_node(
                "capability-guided-templates",
                "Guided Templates",
                product_mapping=guided_templates,
                phase="planner_sandbox_contract_v0",
                file_path="apps/api/app/services/planner_sandbox.py",
                related_endpoints=[
                    "/api/planner-sandbox/templates",
                    "/api/planner-sandbox/templates/{template_id}",
                ],
                related_tests=["apps/api/tests/test_planner_sandbox.py"],
            ),
            self._capability_node(
                "capability-sandbox-drafts",
                "Sandbox Drafts",
                product_mapping=sandbox_drafts,
                phase="planner_sandbox_contract_v0",
                file_path="apps/api/app/services/planner_sandbox.py",
                related_endpoints=[
                    "/api/planner-sandbox/templates",
                    "/api/planner-sandbox/drafts/validate",
                ],
                related_tests=["apps/api/tests/test_planner_sandbox.py"],
            ),
            self._capability_node(
                "capability-compatibility",
                "Compatibility",
                product_mapping=compatibility,
                phase="phase_7",
                file_path="apps/api/app/services/twin_planning_context.py",
                related_endpoints=["/api/twin-planning-context/homes/{home_id}/views/shared-compatibility"],
                related_tests=["apps/api/tests/test_twin_planning_context.py"],
            ),
            self._capability_node(
                "capability-scenario-builder",
                "Scenario Builder",
                product_mapping=scenario_builder,
                phase="phase_3f",
                file_path="apps/api/app/scenarios/router.py",
                related_endpoints=["/api/scenarios", "/api/scenarios/compare"],
                related_tests=["apps/api/tests/test_scenario_revisions.py"],
            ),
            self._capability_node(
                "capability-product-preferences",
                "Product Preferences",
                product_mapping=product_preferences,
                phase="phase_12",
                file_path="apps/api/app/services/product_preferences.py",
                related_endpoints=["/api/product-preferences/homes/{home_id}"],
                related_tests=["apps/api/tests/test_product_preferences.py"],
            ),
            self._capability_node(
                "capability-planning-intelligence",
                "Planning Intelligence",
                product_mapping=planning_intelligence,
                phase="phase_3",
                file_path="apps/api/app/services/twin_planning_context.py",
                related_endpoints=[
                    "/api/twin-planning-context/homes/{home_id}/views/planning-intelligence-readiness",
                    "/api/twin-planning-context/homes/{home_id}/views/advisory-context-assembly",
                ],
                related_tests=["apps/api/tests/test_twin_planning_context.py"],
            ),
            self._capability_node(
                "capability-proposal-options",
                "Proposal Options",
                product_mapping=proposal_options,
                phase="phase_10",
                file_path="apps/api/app/services/proposal_option_sets.py",
                related_endpoints=["/api/proposal-option-sets/homes/{home_id}"],
                related_tests=["apps/api/tests/test_proposal_option_sets.py"],
            ),
            self._capability_node(
                "capability-builder-readiness",
                "Builder Readiness",
                product_mapping=builder_readiness,
                phase="heart_quill_shell_migration",
                file_path="apps/web/src/pages/HeartQuillShellPage.jsx",
                related_endpoints=[
                    "/api/estimate-readiness/homes/{home_id}",
                    "/api/product-preferences/homes/{home_id}",
                    "/api/program-intelligence/homes/{home_id}",
                    "/api/energy-passport/homes/{home_id}",
                ],
                related_tests=[],
            ),
            self._capability_node(
                "capability-contractor-context",
                "Contractor Context",
                product_mapping=contractor_context,
                phase="phase_5_phase_11",
                file_path="apps/api/app/services/contractor_workflow.py",
                related_endpoints=[
                    "/api/contractor-context/homes/{home_id}/planning",
                    "/api/contractor-workflow/homes/{home_id}/readiness",
                ],
                related_tests=["apps/api/tests/test_contractor_workflow.py"],
            ),
            self._capability_node(
                "capability-estimate-readiness",
                "Estimate Readiness",
                product_mapping=estimate_readiness,
                phase="phase_9",
                file_path="apps/api/app/services/estimate_readiness.py",
                related_endpoints=["/api/estimate-readiness/homes/{home_id}"],
                related_tests=["apps/api/tests/test_estimate_readiness.py"],
            ),
            self._capability_node(
                "capability-install-path",
                "Install Path",
                product_mapping=install_path,
                phase="phase_7_phase_8",
                file_path="apps/api/app/services/twin_planning_context.py",
                related_endpoints=[
                    "/api/twin-planning-context/homes/{home_id}/views/shared-compatibility",
                    "/api/twin-planning-context/homes/{home_id}/views/topology-takeoff",
                ],
                related_tests=["apps/api/tests/test_twin_planning_context.py"],
            ),
            self._capability_node(
                "capability-program-intelligence",
                "Program Intelligence",
                product_mapping=program_intelligence,
                phase="phase_15",
                file_path="apps/api/app/services/program_intelligence.py",
                related_endpoints=["/api/program-intelligence/homes/{home_id}"],
                related_tests=["apps/api/tests/test_program_intelligence.py"],
            ),
            self._capability_node(
                "capability-product-catalog",
                "Product Catalog",
                product_mapping=product_catalog,
                phase="deferred_product_catalog_foundation",
                file_path="apps/web/src/pages/HeartQuillShellPage.jsx",
                related_endpoints=["/api/product-library"],
                related_tests=[],
            ),
            self._capability_node(
                "capability-post-install-handoff",
                "Post-Install Handoff",
                product_mapping=post_install_handoff,
                phase="phase_13",
                file_path="apps/api/app/services/post_install.py",
                related_endpoints=["/api/post-install/homes/{home_id}", "/api/crm-handoff/homes/{home_id}"],
                related_tests=["apps/api/tests/test_phase13_post_install_crm.py"],
            ),
            self._capability_node(
                "capability-architecture-cockpit",
                "Product Architecture Cockpit",
                product_mapping=architecture_cockpit,
                phase="architecture_visibility_v1",
                file_path="apps/web/src/pages/ArchitecturePage.jsx",
                related_endpoints=[endpoint],
                related_tests=[test],
            ),
            self._node(
                "frontend-route-architecture",
                "/architecture",
                ArchitectureNodeKind.frontend_page,
                layer="frontend",
                file_path="apps/web/src/pages/ArchitecturePage.jsx",
                phase="architecture_visibility_v1",
                audience="internal",
                related_endpoints=[endpoint],
                related_tests=[test],
                tags=["frontend", "routes", "phases", "hidden_internal"],
            ),
            self._node(
                "frontend-app-router",
                "React App Routes",
                ArchitectureNodeKind.frontend_component,
                layer="frontend",
                file_path="apps/web/src/app/App.jsx",
                audience="internal",
                related_endpoints=[endpoint],
                tags=["frontend", "routes"],
            ),
            self._node(
                "frontend-shell",
                "Shell",
                ArchitectureNodeKind.frontend_component,
                layer="frontend",
                file_path="apps/web/src/components/Shell.jsx",
                audience="homeowner-facing",
                tags=["frontend"],
            ),
            self._node(
                "frontend-page-section",
                "PageSection",
                ArchitectureNodeKind.frontend_component,
                layer="frontend",
                file_path="apps/web/src/components/PageSection.jsx",
                audience="homeowner-facing",
                tags=["frontend"],
            ),
            self._node(
                "frontend-badge",
                "Badge",
                ArchitectureNodeKind.frontend_component,
                layer="frontend",
                file_path="apps/web/src/components/Badge.jsx",
                audience="homeowner-facing",
                tags=["frontend"],
            ),
            self._node(
                "frontend-api-client",
                "Frontend API Client",
                ArchitectureNodeKind.frontend_component,
                layer="frontend",
                file_path="apps/web/src/lib/api.js",
                audience="internal",
                related_endpoints=[endpoint],
                tags=["frontend", "api_routes"],
            ),
            self._node(
                "api-route-system-visibility-architecture",
                "GET /api/system-visibility/architecture",
                ArchitectureNodeKind.api_route,
                layer="api",
                file_path="apps/api/app/system_visibility/router.py",
                phase="architecture_visibility_v1",
                related_endpoints=[endpoint],
                related_tests=[test],
                tags=["api_routes", "backend", "phases"],
            ),
            self._node(
                "backend-main",
                "FastAPI Main Router",
                ArchitectureNodeKind.backend_router,
                layer="backend",
                file_path="apps/api/app/main.py",
                related_endpoints=[endpoint],
                related_tests=[test],
                tags=["backend", "api_routes"],
            ),
            self._node(
                "backend-router-system-visibility",
                "System Visibility Router",
                ArchitectureNodeKind.backend_router,
                layer="backend",
                file_path="apps/api/app/system_visibility/router.py",
                phase="architecture_visibility_v1",
                related_endpoints=[endpoint],
                related_tests=[test],
                tags=["backend", "api_routes"],
            ),
            self._node(
                "backend-service-system-visibility",
                "SystemVisibilityService",
                ArchitectureNodeKind.backend_service,
                layer="backend",
                file_path="apps/api/app/services/system_visibility.py",
                phase="architecture_visibility_v1",
                related_endpoints=[endpoint],
                related_tests=[test],
                tags=["backend", "services", "phases"],
            ),
            self._node(
                "backend-schema-system-visibility",
                "Architecture Visibility Schemas",
                ArchitectureNodeKind.backend_schema,
                layer="backend",
                file_path="apps/api/app/system_visibility/schemas.py",
                phase="architecture_visibility_v1",
                related_endpoints=[endpoint],
                related_tests=[test],
                tags=["backend", "schemas", "phases"],
            ),
            self._node(
                "test-system-visibility",
                "System Visibility Tests",
                ArchitectureNodeKind.test,
                layer="tests",
                file_path=test,
                phase="architecture_visibility_v1",
                related_endpoints=[endpoint],
                tags=["tests", "api_routes", "backend", "phases"],
            ),
            self._node(
                "backend-router-twin-planning-context",
                "Twin Planning Context Router",
                ArchitectureNodeKind.backend_router,
                layer="backend",
                file_path="apps/api/app/twin_planning_context/router.py",
                phase="phase_2b_phase_4",
                audience="homeowner-facing / contractor-facing / internal",
                related_endpoints=[
                    "/api/twin-planning-context/homes/{home_id}",
                    "/api/twin-planning-context/homes/{home_id}/views/topology-takeoff",
                ],
                related_tests=["apps/api/tests/test_twin_planning_context.py"],
                tags=["backend", "api_routes", "phases"],
                product_mapping=energy_twin,
            ),
            self._node(
                "backend-service-twin-planning-context",
                "TwinPlanningContextService",
                ArchitectureNodeKind.backend_service,
                layer="backend",
                file_path="apps/api/app/services/twin_planning_context.py",
                phase="phase_2b_phase_4",
                audience="homeowner-facing / contractor-facing / internal",
                related_tests=["apps/api/tests/test_twin_planning_context.py"],
                tags=["backend", "services", "phases"],
                product_mapping=energy_twin,
            ),
            self._node(
                "backend-schema-twin-planning-context",
                "Twin Planning Context Schemas",
                ArchitectureNodeKind.backend_schema,
                layer="backend",
                file_path="apps/api/app/twin_planning_context/schemas.py",
                phase="phase_2b_phase_4",
                audience="homeowner-facing / contractor-facing / internal",
                related_tests=["apps/api/tests/test_twin_planning_context.py"],
                tags=["backend", "schemas", "phases"],
                product_mapping=energy_twin,
            ),
            self._node(
                "backend-router-estimate-readiness",
                "Estimate Readiness Router",
                ArchitectureNodeKind.backend_router,
                layer="backend",
                file_path="apps/api/app/estimate_readiness/router.py",
                phase="phase_9",
                audience="contractor-facing / internal",
                related_endpoints=["/api/estimate-readiness/homes/{home_id}"],
                related_tests=["apps/api/tests/test_estimate_readiness.py"],
                tags=["backend", "api_routes", "phases"],
                product_mapping=estimate_readiness,
            ),
            self._node(
                "backend-service-estimate-readiness",
                "EstimateReadinessService",
                ArchitectureNodeKind.backend_service,
                layer="backend",
                file_path="apps/api/app/services/estimate_readiness.py",
                phase="phase_9",
                audience="contractor-facing / internal",
                related_tests=["apps/api/tests/test_estimate_readiness.py"],
                tags=["backend", "services", "phases"],
                product_mapping=estimate_readiness,
            ),
            self._node(
                "backend-schema-estimate-readiness",
                "Estimate Readiness Schemas",
                ArchitectureNodeKind.backend_schema,
                layer="backend",
                file_path="apps/api/app/estimate_readiness/schemas.py",
                phase="phase_9",
                audience="contractor-facing / internal",
                related_tests=["apps/api/tests/test_estimate_readiness.py"],
                tags=["backend", "schemas", "phases"],
                product_mapping=estimate_readiness,
            ),
            self._node(
                "backend-router-program-intelligence",
                "Program Intelligence Router",
                ArchitectureNodeKind.backend_router,
                layer="backend",
                file_path="apps/api/app/program_intelligence/router.py",
                phase="phase_15",
                audience="homeowner-facing / contractor-facing / internal",
                related_endpoints=["/api/program-intelligence/homes/{home_id}"],
                related_tests=["apps/api/tests/test_program_intelligence.py"],
                tags=["backend", "api_routes", "phases"],
                product_mapping=program_intelligence,
            ),
            self._node(
                "backend-service-program-intelligence",
                "ProgramIntelligenceService",
                ArchitectureNodeKind.backend_service,
                layer="backend",
                file_path="apps/api/app/services/program_intelligence.py",
                phase="phase_15",
                audience="homeowner-facing / contractor-facing / internal",
                related_tests=["apps/api/tests/test_program_intelligence.py"],
                tags=["backend", "services", "phases"],
                product_mapping=program_intelligence,
            ),
            self._node(
                "backend-schema-program-intelligence",
                "Program Intelligence Schemas",
                ArchitectureNodeKind.backend_schema,
                layer="backend",
                file_path="apps/api/app/program_intelligence/schemas.py",
                phase="phase_15",
                audience="homeowner-facing / contractor-facing / internal",
                related_tests=["apps/api/tests/test_program_intelligence.py"],
                tags=["backend", "schemas", "phases"],
                product_mapping=program_intelligence,
            ),
            self._node(
                "test-twin-planning-context",
                "Twin Planning Context Tests",
                ArchitectureNodeKind.test,
                layer="tests",
                file_path="apps/api/tests/test_twin_planning_context.py",
                phase="phase_2b_phase_4",
                tags=["tests", "backend", "phases"],
            ),
            self._node(
                "test-estimate-readiness",
                "Estimate Readiness Tests",
                ArchitectureNodeKind.test,
                layer="tests",
                file_path="apps/api/tests/test_estimate_readiness.py",
                phase="phase_9",
                tags=["tests", "backend", "phases"],
            ),
            self._node(
                "test-program-intelligence",
                "Program Intelligence Tests",
                ArchitectureNodeKind.test,
                layer="tests",
                file_path="apps/api/tests/test_program_intelligence.py",
                phase="phase_15",
                tags=["tests", "backend", "phases"],
            ),
            self._node(
                "doc-api-contracts",
                "API Contracts",
                ArchitectureNodeKind.doc,
                layer="docs",
                file_path="docs/API_CONTRACTS.md",
                read_write_boundary="documentation_only",
                audience="internal",
                tags=["docs", "api_routes"],
            ),
            self._node(
                "doc-discovery-index",
                "Discovery Index",
                ArchitectureNodeKind.doc,
                layer="docs",
                file_path="discovery-index.md",
                read_write_boundary="documentation_only",
                audience="internal",
                tags=["docs", "phases"],
            ),
            self._node(
                "doc-project-state",
                "Project State",
                ArchitectureNodeKind.doc,
                layer="docs",
                file_path="PROJECT_STATE.md",
                read_write_boundary="documentation_only",
                audience="internal",
                tags=["docs", "phases"],
            ),
            self._node(
                "doc-session-handoff",
                "Session Handoff",
                ArchitectureNodeKind.doc,
                layer="docs",
                file_path="SESSION_HANDOFF.md",
                read_write_boundary="documentation_only",
                audience="internal",
                tags=["docs", "phases"],
            ),
            self._node(
                "doc-phase-15-handoff",
                "Phase 15 Handoff",
                ArchitectureNodeKind.doc,
                layer="docs",
                file_path="docs/handoffs/2026-06-05-phase-15-program-intelligence-closeout.md",
                phase="phase_15",
                read_write_boundary="documentation_only",
                audience="internal",
                related_endpoints=["/api/program-intelligence/homes/{home_id}"],
                tags=["docs", "phases"],
            ),
            self._node(
                "phase-2b-4",
                "Phase 2B-4 Runtime Foundations",
                ArchitectureNodeKind.phase,
                layer="phase",
                file_path="PROJECT_STATE.md",
                phase="phase_2b_phase_4",
                read_write_boundary="documentation_only",
                audience="internal",
                tags=["phases", "backend", "docs"],
            ),
            self._node(
                "phase-9",
                "Phase 9 Estimate Readiness",
                ArchitectureNodeKind.phase,
                layer="phase",
                file_path="docs/handoffs/2026-06-05-phase-9-estimate-readiness-confirmation-gates-closeout.md",
                phase="phase_9",
                read_write_boundary="documentation_only",
                audience="internal",
                related_endpoints=["/api/estimate-readiness/homes/{home_id}"],
                tags=["phases", "backend", "docs"],
            ),
            self._node(
                "phase-15",
                "Phase 15 Program Intelligence",
                ArchitectureNodeKind.phase,
                layer="phase",
                file_path="docs/handoffs/2026-06-05-phase-15-program-intelligence-closeout.md",
                phase="phase_15",
                read_write_boundary="documentation_only",
                audience="internal",
                related_endpoints=["/api/program-intelligence/homes/{home_id}"],
                tags=["phases", "backend", "docs"],
            ),
            self._node(
                "phase-architecture-visibility",
                "Architecture Visibility v1",
                ArchitectureNodeKind.phase,
                layer="phase",
                file_path="apps/api/app/services/system_visibility.py",
                phase="architecture_visibility_v1",
                read_write_boundary="read_only_visibility_metadata",
                audience="internal",
                related_endpoints=[endpoint],
                related_tests=[test],
                tags=["phases", "frontend", "backend", "api_routes"],
            ),
        ]

    def _edges(self) -> List[ArchitectureEdge]:
        return [
            self._edge(
                "edge-ui-home-to-energy-twin",
                "ui-section-home",
                "capability-energy-twin",
                ArchitectureEdgeKind.capability_to_ui_section,
                "groups capability",
            ),
            self._edge(
                "edge-ui-home-to-energy-passport",
                "ui-section-home",
                "capability-energy-passport",
                ArchitectureEdgeKind.capability_to_ui_section,
                "groups capability",
            ),
            self._edge(
                "edge-ui-home-to-readiness",
                "ui-section-home",
                "capability-readiness",
                ArchitectureEdgeKind.capability_to_ui_section,
                "groups capability",
            ),
            self._edge(
                "edge-ui-home-to-home-facts",
                "ui-section-home",
                "capability-home-facts",
                ArchitectureEdgeKind.capability_to_ui_section,
                "groups capability",
            ),
            self._edge(
                "edge-ui-explore-to-goals",
                "ui-section-explore",
                "capability-explore-goals",
                ArchitectureEdgeKind.capability_to_ui_section,
                "groups capability",
            ),
            self._edge(
                "edge-ui-explore-to-learn",
                "ui-section-explore",
                "capability-explore-learn",
                ArchitectureEdgeKind.capability_to_ui_section,
                "groups capability",
            ),
            self._edge(
                "edge-ui-planner-to-guided-templates",
                "ui-section-planner",
                "capability-guided-templates",
                ArchitectureEdgeKind.capability_to_ui_section,
                "groups capability",
            ),
            self._edge(
                "edge-ui-planner-to-sandbox-drafts",
                "ui-section-planner",
                "capability-sandbox-drafts",
                ArchitectureEdgeKind.capability_to_ui_section,
                "groups capability",
            ),
            self._edge(
                "edge-ui-planner-to-scenario-builder",
                "ui-section-planner",
                "capability-scenario-builder",
                ArchitectureEdgeKind.capability_to_ui_section,
                "groups capability",
            ),
            self._edge(
                "edge-ui-planner-to-compatibility",
                "ui-section-deferred-legacy",
                "capability-compatibility",
                ArchitectureEdgeKind.capability_to_ui_section,
                "groups capability",
            ),
            self._edge(
                "edge-ui-planner-to-product-preferences",
                "ui-section-deferred-legacy",
                "capability-product-preferences",
                ArchitectureEdgeKind.capability_to_ui_section,
                "groups capability",
            ),
            self._edge(
                "edge-ui-planner-to-planning-intelligence",
                "ui-section-deferred-legacy",
                "capability-planning-intelligence",
                ArchitectureEdgeKind.capability_to_ui_section,
                "groups capability",
            ),
            self._edge(
                "edge-ui-build-to-proposal-options",
                "ui-section-deferred-legacy",
                "capability-proposal-options",
                ArchitectureEdgeKind.capability_to_ui_section,
                "groups capability",
            ),
            self._edge(
                "edge-ui-builder-to-builder-readiness",
                "ui-section-builder",
                "capability-builder-readiness",
                ArchitectureEdgeKind.capability_to_ui_section,
                "groups capability",
            ),
            self._edge(
                "edge-ui-build-to-contractor-context",
                "ui-section-deferred-legacy",
                "capability-contractor-context",
                ArchitectureEdgeKind.capability_to_ui_section,
                "groups capability",
            ),
            self._edge(
                "edge-ui-build-to-estimate-readiness",
                "ui-section-builder",
                "capability-estimate-readiness",
                ArchitectureEdgeKind.capability_to_ui_section,
                "groups capability",
            ),
            self._edge(
                "edge-ui-build-to-install-path",
                "ui-section-deferred-legacy",
                "capability-install-path",
                ArchitectureEdgeKind.capability_to_ui_section,
                "groups capability",
            ),
            self._edge(
                "edge-ui-build-to-program-intelligence",
                "ui-section-builder",
                "capability-program-intelligence",
                ArchitectureEdgeKind.capability_to_ui_section,
                "groups capability",
            ),
            self._edge(
                "edge-ui-deferred-to-product-catalog",
                "ui-section-deferred-legacy",
                "capability-product-catalog",
                ArchitectureEdgeKind.capability_to_ui_section,
                "groups capability",
            ),
            self._edge(
                "edge-ui-deferred-to-post-install-handoff",
                "ui-section-deferred-legacy",
                "capability-post-install-handoff",
                ArchitectureEdgeKind.capability_to_ui_section,
                "groups capability",
            ),
            self._edge(
                "edge-ui-hidden-to-architecture-cockpit",
                "ui-section-internal-debug",
                "capability-architecture-cockpit",
                ArchitectureEdgeKind.capability_to_ui_section,
                "groups capability",
            ),
            self._edge(
                "edge-twin-router-to-energy-twin-capability",
                "backend-router-twin-planning-context",
                "capability-energy-twin",
                ArchitectureEdgeKind.technical_to_product_capability,
                "supports product capability",
            ),
            self._edge(
                "edge-estimate-router-to-estimate-capability",
                "backend-router-estimate-readiness",
                "capability-estimate-readiness",
                ArchitectureEdgeKind.technical_to_product_capability,
                "supports product capability",
            ),
            self._edge(
                "edge-program-router-to-program-capability",
                "backend-router-program-intelligence",
                "capability-program-intelligence",
                ArchitectureEdgeKind.technical_to_product_capability,
                "supports product capability",
            ),
            self._edge(
                "edge-frontend-app-to-architecture-page",
                "frontend-app-router",
                "frontend-route-architecture",
                ArchitectureEdgeKind.ui_composes_component,
                "registers route",
            ),
            self._edge(
                "edge-architecture-page-to-page-section",
                "frontend-route-architecture",
                "frontend-page-section",
                ArchitectureEdgeKind.ui_composes_component,
                "uses layout sections",
            ),
            self._edge(
                "edge-architecture-page-to-badge",
                "frontend-route-architecture",
                "frontend-badge",
                ArchitectureEdgeKind.ui_composes_component,
                "uses status badges",
            ),
            self._edge(
                "edge-architecture-page-to-api-client",
                "frontend-route-architecture",
                "frontend-api-client",
                ArchitectureEdgeKind.ui_composes_component,
                "loads graph through API client",
            ),
            self._edge(
                "edge-architecture-page-to-api-route",
                "frontend-route-architecture",
                "api-route-system-visibility-architecture",
                ArchitectureEdgeKind.frontend_route_to_api_route,
                "fetches graph",
            ),
            self._edge(
                "edge-main-to-system-visibility-api-route",
                "backend-main",
                "api-route-system-visibility-architecture",
                ArchitectureEdgeKind.route_to_router,
                "includes /api router",
            ),
            self._edge(
                "edge-system-visibility-api-route-to-router",
                "api-route-system-visibility-architecture",
                "backend-router-system-visibility",
                ArchitectureEdgeKind.route_to_router,
                "handled by router",
            ),
            self._edge(
                "edge-system-visibility-router-to-service",
                "backend-router-system-visibility",
                "backend-service-system-visibility",
                ArchitectureEdgeKind.router_to_service,
                "delegates graph construction",
            ),
            self._edge(
                "edge-system-visibility-router-to-schema",
                "backend-router-system-visibility",
                "backend-schema-system-visibility",
                ArchitectureEdgeKind.router_to_schema,
                "declares response model",
            ),
            self._edge(
                "edge-system-visibility-service-to-schema",
                "backend-service-system-visibility",
                "backend-schema-system-visibility",
                ArchitectureEdgeKind.service_to_schema,
                "builds typed graph",
            ),
            self._edge(
                "edge-system-visibility-api-to-tests",
                "api-route-system-visibility-architecture",
                "test-system-visibility",
                ArchitectureEdgeKind.endpoint_to_test,
                "covered by focused tests",
            ),
            self._edge(
                "edge-phase-visibility-to-frontend-page",
                "phase-architecture-visibility",
                "frontend-route-architecture",
                ArchitectureEdgeKind.phase_doc_to_file,
                "implemented by frontend page",
            ),
            self._edge(
                "edge-phase-visibility-to-api-route",
                "phase-architecture-visibility",
                "api-route-system-visibility-architecture",
                ArchitectureEdgeKind.phase_doc_to_file,
                "implemented by read-only endpoint",
            ),
            self._edge(
                "edge-phase-visibility-to-service",
                "phase-architecture-visibility",
                "backend-service-system-visibility",
                ArchitectureEdgeKind.implements_phase,
                "implemented by deterministic service",
            ),
            self._edge(
                "edge-twin-router-to-service",
                "backend-router-twin-planning-context",
                "backend-service-twin-planning-context",
                ArchitectureEdgeKind.router_to_service,
                "delegates derived view construction",
            ),
            self._edge(
                "edge-twin-service-to-schema",
                "backend-service-twin-planning-context",
                "backend-schema-twin-planning-context",
                ArchitectureEdgeKind.service_to_schema,
                "returns typed view contracts",
            ),
            self._edge(
                "edge-twin-endpoint-to-tests",
                "backend-router-twin-planning-context",
                "test-twin-planning-context",
                ArchitectureEdgeKind.endpoint_to_test,
                "covered by regression tests",
            ),
            self._edge(
                "edge-phase-2b-4-to-twin-router",
                "phase-2b-4",
                "backend-router-twin-planning-context",
                ArchitectureEdgeKind.phase_doc_to_file,
                "phase runtime surface",
            ),
            self._edge(
                "edge-phase-2b-4-to-twin-service",
                "phase-2b-4",
                "backend-service-twin-planning-context",
                ArchitectureEdgeKind.phase_doc_to_file,
                "phase service surface",
            ),
            self._edge(
                "edge-estimate-router-to-service",
                "backend-router-estimate-readiness",
                "backend-service-estimate-readiness",
                ArchitectureEdgeKind.router_to_service,
                "delegates readiness construction",
            ),
            self._edge(
                "edge-estimate-service-to-schema",
                "backend-service-estimate-readiness",
                "backend-schema-estimate-readiness",
                ArchitectureEdgeKind.service_to_schema,
                "returns typed readiness contract",
            ),
            self._edge(
                "edge-estimate-endpoint-to-tests",
                "backend-router-estimate-readiness",
                "test-estimate-readiness",
                ArchitectureEdgeKind.endpoint_to_test,
                "covered by focused tests",
            ),
            self._edge(
                "edge-phase-9-doc-to-router",
                "phase-9",
                "backend-router-estimate-readiness",
                ArchitectureEdgeKind.phase_doc_to_file,
                "phase endpoint implementation",
            ),
            self._edge(
                "edge-phase-9-doc-to-service",
                "phase-9",
                "backend-service-estimate-readiness",
                ArchitectureEdgeKind.phase_doc_to_file,
                "phase service implementation",
            ),
            self._edge(
                "edge-program-router-to-service",
                "backend-router-program-intelligence",
                "backend-service-program-intelligence",
                ArchitectureEdgeKind.router_to_service,
                "delegates program intelligence construction",
            ),
            self._edge(
                "edge-program-service-to-schema",
                "backend-service-program-intelligence",
                "backend-schema-program-intelligence",
                ArchitectureEdgeKind.service_to_schema,
                "returns typed program intelligence contract",
            ),
            self._edge(
                "edge-program-endpoint-to-tests",
                "backend-router-program-intelligence",
                "test-program-intelligence",
                ArchitectureEdgeKind.endpoint_to_test,
                "covered by focused tests",
            ),
            self._edge(
                "edge-phase-15-doc-to-router",
                "phase-15",
                "backend-router-program-intelligence",
                ArchitectureEdgeKind.phase_doc_to_file,
                "phase endpoint implementation",
            ),
            self._edge(
                "edge-phase-15-doc-to-service",
                "phase-15",
                "backend-service-program-intelligence",
                ArchitectureEdgeKind.phase_doc_to_file,
                "phase service implementation",
            ),
            self._edge(
                "edge-api-contracts-to-system-visibility",
                "doc-api-contracts",
                "api-route-system-visibility-architecture",
                ArchitectureEdgeKind.phase_doc_to_file,
                "API contract reference point",
            ),
            self._edge(
                "edge-discovery-to-phase-15",
                "doc-discovery-index",
                "phase-15",
                ArchitectureEdgeKind.phase_doc_to_file,
                "phase discovery reference",
            ),
            self._edge(
                "edge-project-state-to-phase-2b-4",
                "doc-project-state",
                "phase-2b-4",
                ArchitectureEdgeKind.phase_doc_to_file,
                "current phase state",
            ),
            self._edge(
                "edge-session-handoff-to-phase-15",
                "doc-session-handoff",
                "phase-15",
                ArchitectureEdgeKind.phase_doc_to_file,
                "latest session continuity",
            ),
            self._edge(
                "edge-phase-15-handoff-to-phase-15",
                "doc-phase-15-handoff",
                "phase-15",
                ArchitectureEdgeKind.phase_doc_to_file,
                "phase closeout reference",
            ),
        ]

    def _summary(self, nodes: List[ArchitectureNode], edges: List[ArchitectureEdge]) -> ArchitectureVisibilitySummary:
        counts: Dict[ArchitectureNodeKind, int] = {
            kind: len([node for node in nodes if node.kind == kind]) for kind in ArchitectureNodeKind
        }
        frontend_node_count = len([node for node in nodes if node.metadata.layer == "frontend"])
        backend_node_count = len([node for node in nodes if node.metadata.layer in {"api", "backend"}])
        return ArchitectureVisibilitySummary(
            node_count=len(nodes),
            edge_count=len(edges),
            frontend_node_count=frontend_node_count,
            backend_node_count=backend_node_count,
            api_route_node_count=counts[ArchitectureNodeKind.api_route],
            service_node_count=counts[ArchitectureNodeKind.backend_service],
            schema_node_count=counts[ArchitectureNodeKind.backend_schema],
            test_node_count=counts[ArchitectureNodeKind.test],
            doc_node_count=counts[ArchitectureNodeKind.doc],
            phase_node_count=counts[ArchitectureNodeKind.phase],
            product_capability_node_count=counts[ArchitectureNodeKind.product_capability],
            ui_section_node_count=counts[ArchitectureNodeKind.ui_section],
        )

    def _capability_exports(self, nodes: List[ArchitectureNode]) -> List[ProductCapabilityExport]:
        exports = []
        for node in nodes:
            if node.kind != ArchitectureNodeKind.product_capability:
                continue
            mapping = node.metadata.product_mapping
            exports.append(
                ProductCapabilityExport(
                    node_id=node.id,
                    product_name=mapping.product_name,
                    homeowner_label=mapping.homeowner_label,
                    contractor_label=mapping.contractor_label,
                    ui_section=mapping.ui_section,
                    ui_card=mapping.ui_card,
                    ui_priority=mapping.ui_priority,
                    visible_in_v1=mapping.visible_in_v1,
                    data_type=mapping.data_type,
                    homeowner_question_answered=mapping.homeowner_question_answered,
                    empty_state_message=mapping.empty_state_message,
                    related_endpoints=node.metadata.related_endpoints,
                    related_tests=node.metadata.related_tests,
                )
            )
        return sorted(exports, key=lambda item: (item.ui_section, item.ui_priority, item.product_name))

    def _inventory(self, capability_exports: List[ProductCapabilityExport]) -> ProductInventorySummary:
        return ProductInventorySummary(
            total_capabilities=len(capability_exports),
            home_capabilities=len([item for item in capability_exports if item.ui_section == "Home"]),
            explore_capabilities=len([item for item in capability_exports if item.ui_section == "Explore"]),
            planner_capabilities=len([item for item in capability_exports if item.ui_section == "Planner"]),
            builder_capabilities=len([item for item in capability_exports if item.ui_section == "Builder"]),
            build_capabilities=len([item for item in capability_exports if item.ui_section == "Builder"]),
            internal_capabilities=len([item for item in capability_exports if item.ui_section == "Internal/Debug"]),
            deferred_capabilities=len([item for item in capability_exports if item.ui_section == "Deferred/Legacy"]),
            visible_in_v1_capabilities=len([item for item in capability_exports if item.visible_in_v1]),
        )

    def _product_groups(self, capability_exports: List[ProductCapabilityExport]) -> List[ProductGroup]:
        groups = []
        for section in ["Home", "Explore", "Planner", "Builder", "Internal/Debug", "Deferred/Legacy"]:
            capabilities = [
                item
                for item in sorted(capability_exports, key=lambda export: (export.ui_priority, export.product_name))
                if item.ui_section == section
            ]
            groups.append(ProductGroup(ui_section=section, capabilities=capabilities))
        return groups

    def _exports(self, capability_exports: List[ProductCapabilityExport]) -> ProductExportBundle:
        return ProductExportBundle(
            ui_capability_map=capability_exports,
            home_section_inventory=[item for item in capability_exports if item.ui_section == "Home"],
            explore_section_inventory=[item for item in capability_exports if item.ui_section == "Explore"],
            planner_section_inventory=[item for item in capability_exports if item.ui_section == "Planner"],
            builder_section_inventory=[item for item in capability_exports if item.ui_section == "Builder"],
            build_section_inventory=[item for item in capability_exports if item.ui_section == "Builder"],
            internal_section_inventory=[item for item in capability_exports if item.ui_section == "Internal/Debug"],
            deferred_section_inventory=[item for item in capability_exports if item.ui_section == "Deferred/Legacy"],
        )

    def build_architecture_graph(self) -> ArchitectureVisibilityGraph:
        nodes = self._nodes()
        edges = self._edges()
        capability_exports = self._capability_exports(nodes)
        return ArchitectureVisibilityGraph(
            scope=ArchitectureVisibilityScope(limitations=ARCHITECTURE_VISIBILITY_LIMITATIONS),
            summary=self._summary(nodes, edges),
            nodes=nodes,
            edges=edges,
            filters=[
                "frontend",
                "backend",
                "api_routes",
                "services",
                "schemas",
                "tests",
                "docs",
                "phases",
                "product",
                "ui",
                "home",
                "explore",
                "planner",
                "builder",
                "build",
                "internal",
                "hidden_internal",
                "deferred",
            ],
            view_modes=[
                "Frontend",
                "Backend",
                "API Routes",
                "Services",
                "Schemas",
                "Tests",
                "Docs",
                "Phases",
                "Product",
                "UI",
            ],
            product_inventory=self._inventory(capability_exports),
            product_groups=self._product_groups(capability_exports),
            exports=self._exports(capability_exports),
            source_basis=ArchitectureVisibilitySourceBasis(
                source_files=[
                    "AGENTS.md",
                    "PROJECT_STATE.md",
                    "SESSION_HANDOFF.md",
                    "discovery-index.md",
                    "docs/API_CONTRACTS.md",
                    "apps/api/app/main.py",
                    "apps/web/src/app/App.jsx",
                    "apps/web/src/lib/uiRegistry.js",
                    "apps/web/src/pages/HeartQuillShellPage.jsx",
                ],
                source_refs=[
                    "apps/api/app/*/router.py",
                    "apps/api/app/services/*.py",
                    "apps/api/app/*/schemas.py",
                    "apps/api/tests/test_*.py",
                    "apps/web/src/pages/*.jsx",
                    "apps/web/src/components/*.jsx",
                    "docs/handoffs/*.md",
                ],
                assumptions=[
                    "v1 graph is manually curated from known route, service, schema, test, and documentation files.",
                    "Product and UI section mappings are product-architecture planning metadata, not a committed frontend redesign.",
                    "Audience labels describe intended visibility language, not authorization enforcement.",
                    "Phase labels are inferred from file names, endpoint history, and discovery-layer documentation.",
                ],
                missing_data=[
                    "No live import graph extraction is performed.",
                    "Not every repository file is represented in v1.",
                    "Frontend tests are not present for the architecture page in the current scope.",
                ],
                limitations=ARCHITECTURE_VISIBILITY_LIMITATIONS,
            ),
        )


system_visibility_service = SystemVisibilityService()
