DEMO_ACCOUNT = {
    "id": "account_demo",
    "email": "demo@residential-energy-planner.local",
    "name": "Demo Homeowner",
    "role": "homeowner",
    "subscription_status": "trialing",
    "plan_type": "demo",
}

SAMPLE_SOURCE_DOCUMENTS = [
    {
        "id": "source_doc_demo_seed_catalog",
        "title": "Demo Seed Product Catalog",
        "source_type": "demo_seed",
        "manufacturer": None,
        "product_model": None,
        "url": None,
        "file_reference": "app/seed/sample_data.py",
        "version": "2026-05-23",
        "published_date": None,
        "retrieved_at": None,
        "verification_status": "unverified",
        "notes": "Demo seed source for placeholder product records. Not factual authority.",
    },
    {
        "id": "source_doc_powerwall_placeholder",
        "title": "Powerwall Placeholder Datasheet Reference",
        "source_type": "manufacturer_datasheet",
        "manufacturer": "Tesla",
        "product_model": "Powerwall Placeholder",
        "url": "https://example.invalid/powerwall-placeholder",
        "file_reference": None,
        "version": "placeholder-reference",
        "published_date": None,
        "retrieved_at": None,
        "verification_status": "unverified",
        "notes": "Placeholder reference only. Do not treat as a verified manufacturer record.",
    },
    {
        "id": "source_doc_user_load_entry",
        "title": "Homeowner Backup Load Note",
        "source_type": "user_entry",
        "manufacturer": None,
        "product_model": None,
        "url": None,
        "file_reference": None,
        "version": None,
        "published_date": None,
        "retrieved_at": None,
        "verification_status": "user_entered",
        "notes": "Represents a homeowner-entered planning assumption.",
    },
    {
        "id": "source_doc_pathway_walkthrough_note",
        "title": "Preliminary Pathway Walkthrough Note",
        "source_type": "user_entry",
        "manufacturer": None,
        "product_model": None,
        "url": None,
        "file_reference": None,
        "version": None,
        "published_date": None,
        "retrieved_at": None,
        "verification_status": "user_entered",
        "notes": "Represents an early routing and distance assumption captured before site verification.",
    },
    {
        "id": "source_doc_internal_rulebook",
        "title": "Internal Planning Rulebook",
        "source_type": "internal_rule",
        "manufacturer": None,
        "product_model": None,
        "url": None,
        "file_reference": "apps/api/app/services",
        "version": "phase_2e_foundation",
        "published_date": None,
        "retrieved_at": None,
        "verification_status": "imported",
        "notes": "Internal planning rules for completeness, advisor reasoning, and transient takeoff derivation.",
    },
]

SAMPLE_DATA_PROVENANCE = [
    {
        "id": "prov_product_pw3_specs",
        "entity_type": "equipment_product",
        "entity_id": "product_pw3",
        "field_name": "specs",
        "source_document_id": "source_doc_powerwall_placeholder",
        "source_type": "manufacturer_datasheet",
        "trust_state": "placeholder",
        "value_snapshot": {"usable_kwh_placeholder": 13.5, "continuous_kw_placeholder": 5.0},
        "confidence_level": "low",
        "verified_at": None,
        "notes": "Placeholder product specs only. Verification has not occurred.",
    },
    {
        "id": "prov_load_001_daily_hours",
        "entity_type": "load",
        "entity_id": "load_001",
        "field_name": "estimated_daily_hours",
        "source_document_id": "source_doc_user_load_entry",
        "source_type": "user_entry",
        "trust_state": "user_created",
        "value_snapshot": {"estimated_daily_hours": 8},
        "confidence_level": "medium",
        "verified_at": None,
        "notes": "User-entered planning assumption for daily refrigerator runtime.",
    },
    {
        "id": "prov_takeoff_line_001_basis",
        "entity_type": "takeoff_line_item",
        "entity_id": "takeoff_line_001",
        "field_name": "quantity",
        "source_document_id": "source_doc_internal_rulebook",
        "source_type": "calculation",
        "trust_state": "derived_estimate",
        "value_snapshot": {"quantity": 20, "basis": "derived from design_001 product assignment"},
        "confidence_level": "medium",
        "verified_at": None,
        "notes": "Illustrative transient takeoff example derived from persisted design composition.",
    },
    {
        "id": "prov_pathway_001_distance",
        "entity_type": "estimated_pathway",
        "entity_id": "pathway_001",
        "field_name": "estimated_distance_ft",
        "source_document_id": "source_doc_pathway_walkthrough_note",
        "source_type": "user_entry",
        "trust_state": "user_created",
        "value_snapshot": {"estimated_distance_ft": 46},
        "confidence_level": "medium",
        "verified_at": None,
        "notes": "Preliminary attic-to-garage routing distance captured during planning walkthrough.",
    },
    {
        "id": "prov_pathway_001_visibility",
        "entity_type": "estimated_pathway",
        "entity_id": "pathway_001",
        "field_name": "visibility_level",
        "source_document_id": "source_doc_internal_rulebook",
        "source_type": "internal_rule",
        "trust_state": "derived_estimate",
        "value_snapshot": {"visibility_level": "low", "basis": "attic_drop route type"},
        "confidence_level": "medium",
        "verified_at": None,
        "notes": "Visibility posture remains a planning estimate until site validation.",
    },
    {
        "id": "prov_pathway_002_distance",
        "entity_type": "estimated_pathway",
        "entity_id": "pathway_002",
        "field_name": "estimated_distance_ft",
        "source_document_id": "source_doc_pathway_walkthrough_note",
        "source_type": "user_entry",
        "trust_state": "user_created",
        "value_snapshot": {"estimated_distance_ft": 140},
        "confidence_level": "low",
        "verified_at": None,
        "notes": "Long detached-building trench distance is still approximate and should be field-checked.",
    },
    {
        "id": "prov_pathway_002_route_difficulty",
        "entity_type": "estimated_pathway",
        "entity_id": "pathway_002",
        "field_name": "route_difficulty",
        "source_document_id": "source_doc_internal_rulebook",
        "source_type": "internal_rule",
        "trust_state": "derived_estimate",
        "value_snapshot": {"route_difficulty": "high", "basis": "detached structure trench route"},
        "confidence_level": "low",
        "verified_at": None,
        "notes": "Difficulty remains a deterministic planning judgment, not a site-verified construction fact.",
    },
]

SAMPLE_RULE_PROVENANCE = [
    {
        "id": "rule_prov_design_completeness",
        "rule_key": "completeness.design_readiness_v1",
        "rule_name": "Design Planning Completeness",
        "source_type": "internal_rule",
        "source_document_id": "source_doc_internal_rulebook",
        "trust_state": "derived_estimate",
        "description": "Planning-only completeness scoring based on missing categories such as panel information, pathways, and equipment strategy.",
        "notes": "Not a code, permit, or engineering completeness rule.",
    },
    {
        "id": "rule_prov_takeoff_design_composition",
        "rule_key": "takeoff.design_composition_v1",
        "rule_name": "Transient Takeoff Derivation",
        "source_type": "internal_rule",
        "source_document_id": "source_doc_internal_rulebook",
        "trust_state": "derived_estimate",
        "description": "Transient takeoff items are derived from persisted design composition and placeholder pricing maps.",
        "notes": "Snapshots remain transient until provenance depth improves.",
    },
    {
        "id": "rule_prov_advisor_derived",
        "rule_key": "advisor.derived_planning_issue",
        "rule_name": "Derived Planning Advisor Issue",
        "source_type": "internal_rule",
        "source_document_id": "source_doc_internal_rulebook",
        "trust_state": "derived_estimate",
        "description": "Advisor issues can be generated from deterministic planning conditions instead of chat inference.",
        "notes": "Planning guidance only.",
    },
    {
        "id": "rule_prov_advisor_whole_home",
        "rule_key": "advisor.whole_home_backup_architecture",
        "rule_name": "Whole-Home Backup Architecture Gap",
        "source_type": "internal_rule",
        "source_document_id": "source_doc_internal_rulebook",
        "trust_state": "derived_estimate",
        "description": "Flags whole-home backup goals that lack explicit backup architecture records.",
        "notes": None,
    },
    {
        "id": "rule_prov_advisor_detached_structure",
        "rule_key": "advisor.detached_structure_pathway",
        "rule_name": "Detached Structure Pathway Gap",
        "source_type": "internal_rule",
        "source_document_id": "source_doc_internal_rulebook",
        "trust_state": "derived_estimate",
        "description": "Flags detached structures that do not have linked pathway planning.",
        "notes": None,
    },
    {
        "id": "rule_prov_advisor_battery_inverter",
        "rule_key": "advisor.battery_without_inverter",
        "rule_name": "Battery Without Inverter Strategy",
        "source_type": "internal_rule",
        "source_document_id": "source_doc_internal_rulebook",
        "trust_state": "derived_estimate",
        "description": "Flags battery assignments that lack inverter or hybrid inverter context.",
        "notes": None,
    },
    {
        "id": "rule_prov_advisor_generator_transfer",
        "rule_key": "advisor.generator_transfer_strategy",
        "rule_name": "Generator Transfer Strategy Gap",
        "source_type": "internal_rule",
        "source_document_id": "source_doc_internal_rulebook",
        "trust_state": "derived_estimate",
        "description": "Flags generator-assisted goals that lack gateway, transfer, or disconnect strategy.",
        "notes": None,
    },
    {
        "id": "rule_prov_advisor_expansion_capacity",
        "rule_key": "advisor.expansion_panel_capacity",
        "rule_name": "Expansion Panel Capacity Gap",
        "source_type": "internal_rule",
        "source_document_id": "source_doc_internal_rulebook",
        "trust_state": "derived_estimate",
        "description": "Flags expansion-ready designs that do not record spare panel capacity.",
        "notes": None,
    },
    {
        "id": "rule_prov_advisor_visible_conduit",
        "rule_key": "advisor.visible_conduit_assumption",
        "rule_name": "Visible Conduit Assumption",
        "source_type": "internal_rule",
        "source_document_id": "source_doc_internal_rulebook",
        "trust_state": "derived_estimate",
        "description": "Flags pathway assumptions that likely lead to visible conduit or exposed infrastructure.",
        "notes": None,
    },
    {
        "id": "rule_prov_advisor_trench",
        "rule_key": "advisor.long_trench_complexity",
        "rule_name": "Long Trench Complexity",
        "source_type": "internal_rule",
        "source_document_id": "source_doc_internal_rulebook",
        "trust_state": "derived_estimate",
        "description": "Flags long trench pathways that increase labor complexity and uncertainty.",
        "notes": None,
    },
    {
        "id": "rule_prov_advisor_battery_distance",
        "rule_key": "advisor.battery_distance_from_service",
        "rule_name": "Battery Distance From Service",
        "source_type": "internal_rule",
        "source_document_id": "source_doc_internal_rulebook",
        "trust_state": "derived_estimate",
        "description": "Flags battery siting that appears far from the main distribution context.",
        "notes": None,
    },
    {
        "id": "rule_prov_recommendation_profiles",
        "rule_key": "recommendation.resilience_profile_matrix_v1",
        "rule_name": "Resilience Recommendation Profile Matrix",
        "source_type": "internal_rule",
        "source_document_id": "source_doc_internal_rulebook",
        "trust_state": "derived_estimate",
        "description": "Maps current design signals into resilience recommendation profiles such as Critical / Efficient, Balanced, Conservative, and Premium / Future-Ready.",
        "notes": "Planning guidance only. Does not expose engineering sizing formulas.",
    },
    {
        "id": "rule_prov_recommendation_backup_load_selection",
        "rule_key": "recommendation.backup_load_selection_v1",
        "rule_name": "Deterministic Backup Load Selection",
        "source_type": "internal_rule",
        "source_document_id": "source_doc_internal_rulebook",
        "trust_state": "derived_estimate",
        "description": "Selects the current planning backup scope from recorded essential and preferred loads without inferring broader outage intent than the structured load grouping supports.",
        "notes": "Planning guidance only. Does not imply final transfer, inverter, or generator design.",
    },
    {
        "id": "rule_prov_recommendation_battery_sizing",
        "rule_key": "recommendation.profile_battery_sizing_v1",
        "rule_name": "Profile-Backed Battery Planning Range",
        "source_type": "internal_rule",
        "source_document_id": "source_doc_internal_rulebook",
        "trust_state": "derived_estimate",
        "description": "Derives planning-only battery capacity ranges from backup-load modeling plus profile-based autonomy, reserve, and growth postures.",
        "notes": "Planning guidance only. Not a final engineered storage design.",
    },
    {
        "id": "rule_prov_recommendation_solar_sizing",
        "rule_key": "recommendation.profile_solar_sizing_v1",
        "rule_name": "Profile-Backed Solar Recovery Range",
        "source_type": "internal_rule",
        "source_document_id": "source_doc_internal_rulebook",
        "trust_state": "derived_estimate",
        "description": "Derives planning-only solar capacity ranges from current backup-load modeling, battery recovery posture, and low-solar assumptions.",
        "notes": "Planning guidance only. Not a final production or seasonal engineering study.",
    },
    {
        "id": "rule_prov_recommendation_solar_site_adjustment",
        "rule_key": "recommendation.profile_solar_site_adjustment_v1",
        "rule_name": "Coarse Site-Aware Solar Adjustment",
        "source_type": "internal_rule",
        "source_document_id": "source_doc_internal_rulebook",
        "trust_state": "derived_estimate",
        "description": "Applies coarse planning-only solar range adjustments for recorded roof placement, unmodeled shading, coarse seasonal region posture, and install-path realism.",
        "notes": "Planning guidance only. Uses fallback postures when site-production inputs are incomplete.",
    },
    {
        "id": "rule_prov_recommendation_roof_geometry_readiness",
        "rule_key": "recommendation.roof_geometry_readiness_v1",
        "rule_name": "Roof Geometry Readiness Classification",
        "source_type": "internal_rule",
        "source_document_id": "source_doc_internal_rulebook",
        "trust_state": "derived_estimate",
        "description": "Classifies whether solar roof-capacity posture is only inferred from placement records or could later be grounded by measured geometry such as traced polygons, roof planes, and usable-area estimates.",
        "notes": "Planning guidance only. Does not calculate roof area or measured production capacity.",
    },
    {
        "id": "rule_prov_recommendation_panel_service_architecture",
        "rule_key": "recommendation.panel_service_preliminary_architecture_v1",
        "rule_name": "Preliminary Panel and Service Architecture",
        "source_type": "internal_rule",
        "source_document_id": "source_doc_internal_rulebook",
        "trust_state": "derived_estimate",
        "description": "Maps current panel, service, load-grouping, pathway, and architecture signals into a preliminary backup-architecture posture before inverter, smart-panel modifier, or generator sizing layers are introduced.",
        "notes": "Planning guidance only. Does not confirm busbar compliance, interlock details, or final backup architecture engineering.",
    },
    {
        "id": "rule_prov_advisor_ecosystems",
        "rule_key": "advisor.mixed_ecosystems",
        "rule_name": "Mixed Ecosystem Planning",
        "source_type": "internal_rule",
        "source_document_id": "source_doc_internal_rulebook",
        "trust_state": "derived_estimate",
        "description": "Flags designs that mix multiple ecosystems and may complicate support or controls assumptions.",
        "notes": None,
    },
    {
        "id": "rule_prov_seeded_issue",
        "rule_key": "advisor.seeded_compatibility_issue",
        "rule_name": "Seeded Compatibility Issue",
        "source_type": "demo_seed",
        "source_document_id": "source_doc_demo_seed_catalog",
        "trust_state": "demo_seed",
        "description": "Compatibility issues seeded for demo continuity, not verified engineering guidance.",
        "notes": None,
    },
]

SAMPLE_HOME = {
    "id": "home_001",
    "account_id": "account_demo",
    "name": "Cedar Ridge Residence",
    "address_line_1": "123 Placeholder Lane",
    "address_line_2": None,
    "city": "Placerville",
    "state": "CA",
    "postal_code": "95667",
    "country": "US",
    "utility_provider": "Utility provider placeholder",
    "service_size": 200,
    "buildings": [
        {
            "id": "building_main",
            "home_id": "home_001",
            "name": "Main House",
            "type": "main_house",
            "approximate_distance_from_main_service": 0,
            "notes": "Primary living structure.",
        },
        {
            "id": "building_shop",
            "home_id": "home_001",
            "name": "Workshop",
            "type": "workshop",
            "approximate_distance_from_main_service": 140,
            "notes": "Detached workspace with future equipment growth potential.",
        },
    ],
    "panels": [
        {
            "id": "panel_main",
            "home_id": "home_001",
            "building_id": "building_main",
            "panel_type": "main_service_panel",
            "amperage": 200,
            "busbar_rating": 225,
            "breaker_spaces_total": 40,
            "breaker_spaces_available": 6,
            "indoor_outdoor": "indoor",
            "notes": "Placeholder panel data for planning only.",
        }
    ],
    "notes": "Example property used to demonstrate persistent house modeling.",
}

SAMPLE_LOADS = [
    {
        "id": "load_001",
        "home_id": "home_001",
        "building_id": "building_main",
        "name": "Refrigerator Circuit",
        "category": "kitchen",
        "running_watts": 180,
        "surge_watts": 900,
        "estimated_daily_hours": 8,
        "backup_priority": "essential",
        "phase_type": "split_phase",
        "notes": "Representative planning load.",
    },
    {
        "id": "load_002",
        "home_id": "home_001",
        "building_id": "building_main",
        "name": "Well Pump",
        "category": "water",
        "running_watts": 1000,
        "surge_watts": 3000,
        "estimated_daily_hours": 2,
        "backup_priority": "preferred",
        "phase_type": "split_phase",
        "notes": "Placeholder surge estimate.",
    },
    {
        "id": "load_003",
        "home_id": "home_001",
        "building_id": "building_shop",
        "name": "Workshop Tools Subpanel",
        "category": "workshop",
        "running_watts": 2500,
        "surge_watts": 4000,
        "estimated_daily_hours": 3,
        "backup_priority": "optional",
        "phase_type": "split_phase",
        "notes": "Bundle placeholder representing future tools growth.",
    },
]

SAMPLE_EQUIPMENT_LOCATIONS = [
    {
        "id": "location_roof_south",
        "home_id": "home_001",
        "building_id": "building_main",
        "name": "South Roof Plane",
        "location_type": "roof",
        "approximate_coordinates": "placeholder",
        "notes": "Future roof geometry and obstruction modeling belongs here.",
    },
    {
        "id": "location_garage_battery",
        "home_id": "home_001",
        "building_id": "building_main",
        "name": "Garage Battery Wall",
        "location_type": "battery_area",
        "approximate_coordinates": "placeholder",
        "notes": "Indoor battery staging placeholder.",
    },
    {
        "id": "location_shop_pad",
        "home_id": "home_001",
        "building_id": "building_shop",
        "name": "Workshop Generator Pad",
        "location_type": "generator_pad",
        "approximate_coordinates": "placeholder",
        "notes": "Future generator siting placeholder.",
    },
]

SAMPLE_PRODUCTS = [
    {
        "id": "product_pw3",
        "manufacturer": "Tesla",
        "model": "Powerwall Placeholder",
        "product_type": "battery",
        "ecosystem": "Tesla",
        "specs": {
            "usable_kwh_placeholder": 13.5,
            "continuous_kw_placeholder": 5.0,
            "note": "Placeholder only. Replace with verified Tesla documentation before use.",
        },
        "documentation_url": None,
        "notes": "Seed record for Tesla ecosystem planning.",
    },
    {
        "id": "product_tesla_gateway",
        "manufacturer": "Tesla",
        "model": "Backup Gateway Placeholder",
        "product_type": "gateway",
        "ecosystem": "Tesla",
        "specs": {
            "service_integration": "placeholder",
            "note": "Placeholder only. Verify supported service configurations.",
        },
        "documentation_url": None,
        "notes": "Gateway placeholder paired with Powerwall-style ecosystem planning.",
    },
    {
        "id": "product_enphase_micro",
        "manufacturer": "Enphase",
        "model": "IQ Microinverter Placeholder",
        "product_type": "microinverter",
        "ecosystem": "Enphase",
        "specs": {
            "ac_output_watts_placeholder": 325,
            "note": "Placeholder only. Do not assume current product output values.",
        },
        "documentation_url": None,
        "notes": "Seed record for Enphase microinverter ecosystem.",
    },
    {
        "id": "product_eg4_hybrid",
        "manufacturer": "EG4",
        "model": "Hybrid Inverter Placeholder",
        "product_type": "hybrid_inverter",
        "ecosystem": "EG4",
        "specs": {
            "inverter_kw_placeholder": 12,
            "battery_coupling": "placeholder",
            "note": "Placeholder only. Replace with verified EG4 product data.",
        },
        "documentation_url": None,
        "notes": "Seed record for EG4 hybrid ecosystem.",
    },
    {
        "id": "product_schneider_panel",
        "manufacturer": "Schneider Electric",
        "model": "Smart Energy Panel Placeholder",
        "product_type": "smart_panel",
        "ecosystem": "Schneider",
        "specs": {
            "load_control_zones_placeholder": 12,
            "note": "Placeholder only. Verify panel and control capabilities.",
        },
        "documentation_url": None,
        "notes": "Placeholder for Schneider smart energy planning.",
    },
    {
        "id": "product_ecoflow_system",
        "manufacturer": "EcoFlow",
        "model": "Home Backup System Placeholder",
        "product_type": "battery",
        "ecosystem": "EcoFlow",
        "specs": {
            "expandable_storage_placeholder": True,
            "note": "Placeholder only. Replace with verified EcoFlow system data.",
        },
        "documentation_url": None,
        "notes": "Placeholder for modular EcoFlow system planning.",
    },
    {
        "id": "product_generic_panel",
        "manufacturer": "Generic",
        "model": "400W Solar Panel Placeholder",
        "product_type": "solar_panel",
        "ecosystem": "Other",
        "specs": {
            "stc_watts_placeholder": 400,
            "dimensions": "placeholder",
            "note": "Placeholder module for generic array layout discussions.",
        },
        "documentation_url": None,
        "notes": "Generic solar panel placeholder with non-authoritative values.",
    },
    {
        "id": "product_generic_generator",
        "manufacturer": "Generic",
        "model": "Standby Generator Placeholder",
        "product_type": "generator",
        "ecosystem": "Generac",
        "specs": {
            "nameplate_kw_placeholder": 18,
            "fuel_type": "placeholder",
            "note": "Placeholder only. Verify real product specs and transfer requirements.",
        },
        "documentation_url": None,
        "notes": "Generic generator placeholder for generator-assisted design pathways.",
    },
]

SAMPLE_DESIGNS = [
    {
        "id": "design_001",
        "home_id": "home_001",
        "name": "Phase 1 Partial Backup",
        "design_goal": "partial_backup",
        "architecture_type": "ac_coupled",
        "status": "draft",
        "notes": "Designed to preserve an expansion path into whole-home resilience.",
        "equipment": [
            {
                "design_id": "design_001",
                "product_id": "product_generic_panel",
                "quantity": 20,
                "location_id": "location_roof_south",
                "role_in_system": "primary_generation",
                "notes": "Placeholder module count.",
            },
            {
                "design_id": "design_001",
                "product_id": "product_pw3",
                "quantity": 1,
                "location_id": "location_garage_battery",
                "role_in_system": "backup_storage",
                "notes": "Single battery starter configuration.",
            },
        ],
    },
    {
        "id": "design_002",
        "home_id": "home_001",
        "name": "Workshop-Ready Hybrid",
        "design_goal": "workshop_ready",
        "architecture_type": "hybrid",
        "status": "exploratory",
        "notes": "Intended to balance present backup needs with future workshop expansion.",
        "equipment": [
            {
                "design_id": "design_002",
                "product_id": "product_eg4_hybrid",
                "quantity": 1,
                "location_id": "location_garage_battery",
                "role_in_system": "system_control",
                "notes": "Placeholder hybrid inverter layout.",
            },
            {
                "design_id": "design_002",
                "product_id": "product_generic_generator",
                "quantity": 1,
                "location_id": "location_shop_pad",
                "role_in_system": "generator_assist",
                "notes": "Placeholder standby generator add-on.",
            },
        ],
    },
]

SAMPLE_COMPATIBILITY_ISSUES = [
    {
        "id": "issue_001",
        "design_id": "design_001",
        "severity": "warning",
        "category": "expansion",
        "issue": "Single starter battery may not cover future workshop growth.",
        "why_it_matters": "A design that works today can become a dead end if future storage expansion or higher surge support is constrained.",
        "possible_solutions": [
            "Reserve wall space and conduit for added storage.",
            "Evaluate architectures that support modular battery expansion.",
            "Separate workshop loads into a future-ready subpanel strategy.",
        ],
        "tradeoff": "Lower upfront cost now may create retrofit labor and equipment replacement later.",
        "related_equipment_ids": ["product_pw3"],
    },
    {
        "id": "issue_002",
        "design_id": "design_002",
        "severity": "info",
        "category": "install_complexity",
        "issue": "Detached workshop integration likely increases trenching and coordination scope.",
        "why_it_matters": "Multi-building systems often carry higher labor variability, extra disconnecting means, and more coordination around routing and service strategy.",
        "possible_solutions": [
            "Keep phase one focused on the main house and reserve a workshop expansion path.",
            "Route empty conduit during early site work.",
            "Model workshop as a separate backed-up zone.",
        ],
        "tradeoff": "Early infrastructure work can raise phase-one cost while reducing future disruption.",
        "related_equipment_ids": ["product_eg4_hybrid", "product_generic_generator"],
    },
]

SAMPLE_SCENARIOS = [
    {
        "id": "scenario_001",
        "home_id": "home_001",
        "name": "Budget-Conscious Starter System",
        "description": "Solar plus one battery sized around essential loads with future expansion left open.",
        "linked_design_id": "design_001",
        "upfront_cost_placeholder": 25000,
        "future_expansion_score": 0.72,
        "install_complexity_score": 0.28,
        "backup_capability_score": 0.58,
        "notes": "Placeholder scoring only.",
    },
    {
        "id": "scenario_002",
        "home_id": "home_001",
        "name": "Workshop-Ready Resilience Path",
        "description": "Hybrid architecture keeping generator assistance available for future detached loads.",
        "linked_design_id": "design_002",
        "upfront_cost_placeholder": 39000,
        "future_expansion_score": 0.81,
        "install_complexity_score": 0.44,
        "backup_capability_score": 0.67,
        "notes": "Placeholder scoring only.",
    },
]

SAMPLE_TAKEOFF = {
    "request": {
        "id": "takeoff_001",
        "design_id": "design_001",
        "status": "placeholder",
        "requested_by": "system_seed",
        "notes": "Illustrative takeoff request only.",
    },
    "line_items": [
        {
            "id": "takeoff_line_001",
            "takeoff_request_id": "takeoff_001",
            "category": "modules",
            "item_name": "400W Solar Panel Placeholder",
            "quantity": 20,
            "unit": "each",
            "unit_cost_placeholder": 250,
            "total_cost_placeholder": 5000,
            "assumptions": "Placeholder module count from seed design.",
            "notes": "Not a purchasable takeoff yet.",
        },
        {
            "id": "takeoff_line_002",
            "takeoff_request_id": "takeoff_001",
            "category": "storage",
            "item_name": "Battery Placeholder",
            "quantity": 1,
            "unit": "each",
            "unit_cost_placeholder": 9000,
            "total_cost_placeholder": 9000,
            "assumptions": "Placeholder storage quantity.",
            "notes": "Requires verified product mapping.",
        },
    ],
}

SAMPLE_LOAD_TEMPLATES = [
    {
        "id": "load_template_fridge",
        "account_id": "account_demo",
        "name": "Essential Refrigerator",
        "category": "kitchen",
        "running_watts": 180,
        "surge_watts": 900,
        "estimated_daily_hours": 8,
        "backup_priority": "essential",
        "phase_type": "split_phase",
        "notes": "Starter residential refrigeration template.",
    },
    {
        "id": "load_template_well_pump",
        "account_id": "account_demo",
        "name": "Preferred Well Pump",
        "category": "water",
        "running_watts": 1000,
        "surge_watts": 3000,
        "estimated_daily_hours": 2,
        "backup_priority": "preferred",
        "phase_type": "split_phase",
        "notes": "Placeholder template for well pump planning.",
    },
    {
        "id": "load_template_wifi",
        "account_id": "account_demo",
        "name": "Essential Router + Modem",
        "category": "communications",
        "running_watts": 35,
        "surge_watts": 50,
        "estimated_daily_hours": 24,
        "backup_priority": "essential",
        "phase_type": "single_phase",
        "notes": "Useful for Essential Backup starter bundle.",
    },
    {
        "id": "load_template_living_room",
        "account_id": "account_demo",
        "name": "Comfort Living Room Circuits",
        "category": "comfort",
        "running_watts": 250,
        "surge_watts": 400,
        "estimated_daily_hours": 5,
        "backup_priority": "preferred",
        "phase_type": "split_phase",
        "notes": "Useful for Comfort Backup planning.",
    },
    {
        "id": "load_template_heat_pump",
        "account_id": "account_demo",
        "name": "Whole Home Heat Pump Placeholder",
        "category": "hvac",
        "running_watts": 3500,
        "surge_watts": 5000,
        "estimated_daily_hours": 8,
        "backup_priority": "preferred",
        "phase_type": "split_phase",
        "notes": "Whole Home Planning placeholder only.",
    },
    {
        "id": "load_template_ev",
        "account_id": "account_demo",
        "name": "Optional EV Charging Placeholder",
        "category": "ev",
        "running_watts": 7200,
        "surge_watts": 7200,
        "estimated_daily_hours": 2,
        "backup_priority": "optional",
        "phase_type": "split_phase",
        "notes": "Optional add-on planning template.",
    },
]

SAMPLE_DESIGN_GOAL_PRESETS = [
    {
        "id": "preset_partial_backup",
        "name": "Partial Backup Starter",
        "design_goal": "partial_backup",
        "architecture_type": "ac_coupled",
        "summary": "Focus on essential and preferred loads while preserving a future expansion path.",
        "notes": "Good fit for phase-one resilience planning.",
    },
    {
        "id": "preset_workshop_ready",
        "name": "Workshop Ready Hybrid",
        "design_goal": "workshop_ready",
        "architecture_type": "hybrid",
        "summary": "Preserve detached-load growth while balancing present-day backup needs.",
        "notes": "Useful when outbuildings will matter later.",
    },
]

SAMPLE_ESTIMATED_PATHWAYS = [
    {
        "id": "pathway_001",
        "home_id": "home_001",
        "design_id": "design_001",
        "name": "Starter Solar + Battery Path",
        "description": "Entry pathway focused on essential loads and phased storage growth.",
        "lifecycle_stage": "phase_1",
        "source_location": "South Roof Plane",
        "destination_location": "Garage Battery Wall",
        "estimated_distance_ft": 46,
        "route_type": "attic_drop",
        "route_difficulty": "moderate",
        "visibility_level": "low",
        "confidence_level": "medium",
        "upfront_cost_placeholder": 25000,
        "estimated_monthly_savings_placeholder": 145,
        "resilience_score": 0.58,
        "notes": "Placeholder pathway economics only.",
    },
    {
        "id": "pathway_002",
        "home_id": "home_001",
        "design_id": "design_002",
        "name": "Workshop Resilience Expansion Path",
        "description": "Higher-complexity path preserving detached-load support and generator assist.",
        "lifecycle_stage": "phase_2",
        "source_location": "Main House MSP",
        "destination_location": "Workshop Generator Pad",
        "estimated_distance_ft": 140,
        "route_type": "trench_route",
        "route_difficulty": "high",
        "visibility_level": "medium",
        "confidence_level": "low",
        "upfront_cost_placeholder": 39000,
        "estimated_monthly_savings_placeholder": 180,
        "resilience_score": 0.67,
        "notes": "Placeholder pathway for future comparison tooling.",
    },
]
